* What is evolution? How has evolution been proven out as a scientific theory?  What is the evidence for it?
  Evolution is the process of change over time. Evolution has been
proven as a scientific theory by conducting various experiments to
prove that the distinguishable differences we see in biological
organisms are due to generations worth of evolution where organisms
underwent mutations in successive generations to adapt themselves to
the natural environment around them. It's a scientific theory. So,
there are experiments that we can conduct at any point in time to
derive evidence for the theory. One example is Gregor Mendel's
experiment with peas. 

* How do macro- and micro- evolution differ?  How are they similar?
  Microevolution is simply a change in the gene frequency within a
population. Macroevolution refers to evolution at the species level.
They are similar in that they are accounting for change in the
biological organism. They are different in the level with which they
view the change. A microevolution example would be change in
coloration of a beetle from one generation to the next. The number of
beetles with the different color gene might go up drastically in one
generation from the previous. This could be due to variety of
environmental factors like abundance of sparrows that feed on the
beetles with light color. A macroevolution example would be
documenting the change of wolves to dogs. This requires a view over
several generations. It's often realized after the change has already occured.

* How has the process of the scientific method helped understand more and more about the origins and ebb and flow of life on Earth?
  The process of scientific method has allowed to collect evidence for
  the theory of evolution over the entire lifetime of earth by
  allowing us to conduct experiments of any size, number, volume and
  analyze the results thoroughly to account for the existence of life
  on earth and all the different ebbs and flows within the biological
  species. There are unidentified species in the world but the
  scientific process is the best method humans have "evolved" to
  accept as the best ground to place their decisions on.
* What is taxonomy and why is it important on science?
  Taxonomy deals with the classification of biological organisms on
  earth. There are millions of biological organisms that have
  inhabited this earth. To categorize them and study them is important
  to understand how life on earth has taken it's forms and how it
  continues to take form. It's important in science for this very
  reason. There are several levels at which taxonomy brings about change.
* What are your biggest take-home lessons and points from this module? How has it changed or solidified your views of life on this ball of wonder we call Earth?
  My biggest take home lesson from this module is that categorizing
  organisms is not an easy task. It takes a lot of understanding of
  not just the biological species at hand but also the context with
  which to view them matters for placing them in the right
  classification among other organisms. My second big takeaway is that
  evolution is a fascinating explanation for life on earth and has
  helped humans understand a lot of themselves and also about life on
  earth. My third takeaway is that insect evolution is a great glimpse
  of all the complications involved with evolution. The evolution of
  insect wings, exoskeleton, their tiny stature and reproductive
  abilities are all fascinating when viewed with the lenses of evolution.
