* Geologic setting (plate tectonics setting)
Mayon Volcano in Phillipines. This volcano sits at the convergent
plate boundary. Lighter continental plate floats above denser oceanic
plate which subducts, allowing magma from under to rise up as it gets
cooled by the subducting oceanic plates. This volcano is part of the
pacific ring of fire.

* Associated volcanic landforms (what type of volcano? Any special other volcanic features around like columnar jointing, lava tubes, or cinder cones?)
Stratovolcano. Seven cinder cones on the southern/southwestern slopes.
Volcano shows cone structure
* Assocated materials (if lava flows, what composition? What minerals would you find; if lahars, ash, or pyroclastic flow, what composition and type of material)
Lava: augite-hypersthene-andesite
Pyroclastic flows: ardente; block and ash deposits
Breadcrust bombs: ash and lapili matrix
Lahars: Olivine-augite basalt

* What about this particular volcano interested you?
I wanted to look into volcanoes in Phillipines since my housemate has
studied there so I could ask him about the volcanoes there. When I
started looking, Mayon volcano came up as the most active volcano.

* Descriptions and labels of key characteristics.
Major Rock types
Andesite / Basaltic Andesite
Basalt / Picro-Basalt

** Location: Albay Gulf NW of Legazpi City, Philippines. 
** Physical characteristics: Steep upper slopes with a small summit crater. 
** Recorded eruptions: Since 1616 CE 
** Erupted Materials: Strombolian to basaltic Plinian, with cyclical activity beginning with basaltic eruptions, followed by longer term andesitic lava flows. 

Eruptions occur predominately from the central conduit and have also produced lava flows that travel far down the
flanks. Pyroclastic flows and mudflows have commonly swept down many
of the approximately 40 ravines that radiate from the summit and have
often damaged populated lowland areas. 

* Scale
2462 m / 8077 ft

* Resources
1. Smithsonian Institute: https://volcano.si.edu/volcano.cfm?vn=273030
2. Wikipedia: https://en.wikipedia.org/wiki/Mayon

