**** Formulate one argument that supports or refutes this statement and share with the group:

"I would argue that one of the most important things that cognitive science has done in recent years is show that the chasm between relativists (that is, those who focus on linguistic or cultural constraints on the mind) and universalists (those who are more concerned with innate psycho-biological constraints) has now become narrower, if not closed. To put things in other terms, it seems that human beings, and their cultures, can be quite creative and imaginative—almost limitless, it would appear at first glance—but we cannot think about anything without restraint."

The claim is that cognitive science has closed the gap between relativists and universalists. What did cognitive science do? Make ourselves understand better. The only supporting claim to the statement we are given is that we cannot think about anything without restraint. Where does this restraint come from? Is it a physical/biological restraint? Is it a cultural restraint, as Everett describes(Ahearn 2017, Page 137)? Is it a restriction of the tools humans have come up with (for example: language)? A physical/biological restraint could be refuted with evolution of human mind. A cultural restraint, is a restraint of the society that we live in. For example, the infusion of business related terms in our daily use of language. A specific case is the use of words like "deal" to mean "Agreed". Culture doesn't have a single restraint in that it's always changing in my view. Culture, as I understand and believe, is more free flowing than can be contained with a set of rules. A linguistic restraint(or a restraint because of the tools humans have come up with to construct thought) is a little bit to refute. Ahearn writes that linguistic anthropologists believe that language is a symbolic guide to culture and the three - language, culture and thought are intertwined. If culture and thought aren't restrained, then language that people come up with to facilitate it need not be perceived as restrained as well. I'm willing to accept that there are boundaries to the extent human thought but has cognitive science proved that the boundaries are rigid and unmovable? 

**** How might a linguistic determinist (e.g., Whorf, Sapir, or Lucy), a universalist (e.g., Chomsky), and a cultural determinist (Witherspoon or Everett) respond to your argument?
   

3) What are your thoughts on some of your classmates' arguments?
