**** According to Klein, is neoliberalism consistent with democratic principles?
     According to Klein, neoliberalism is antithetical to democratic principles. Klein argues that by wanting a more Laissez-Faire approach to markets, economists like Milton Friedman, wanted to create an economy where companies or market leaders were given a more or less free run, compared to the rest of the population. If a democratically elected government is the representation of the people, and that government has less power in how the markets function, then people don't have much power/say in the neoliberal societies. Under neoliberalism, there is no limit on wealth accumulation, creating more inequalities and sharper divide between the rich and poor, which is also not consistent with democratic principles. In neoliberalism, because there is less regulation, there is little room/regulations for providing worker rights or any collective exercise of human rights that is not profitable/favorable to the functioning of the market. An example, would be workers of Exxon, Amazon wanting to change the company's policies but unable to do so, eventhough the majority is on their end. The unequal distribution of rights in a company, and thereby in the neoliberal societies, is fundamentally antithetical to democratic principles
