Module 3 focuses on the methods we use in linguistic anthropology to conduct research. How do we set these studies? Who are our main informants? What is important to the design of research? Why should we consider ethnical practices? This is what we'll be talking about in this modue.

* How would you select your informant(s)?
Who will you observe?
Why would you choose certain types of individuals over others?
What methodologies from the reading will you most likely use and why?

If I were to conduct a linguistic anthropology field research, I would try and learn the local language as much as possible and see what areas of the research could be better done with the aid of an informant or research assistant. As Ahearn mentions, doing all parts of the research by the researcher is daunting and in many cases just not possible. So, selecting research assistants has to be done carefully. Informing them of the bounds of the research, not to keep them within it but to question the bounds and help us identify where it has to be made flexible. Also, equipping the research assistant of the ethical considerations and working towards identifying a shared ethical standards would be helpful and might also help better in getting shared consent from the participants of the research.

The participants of the research are primarily determined by the type of questions the research poses. But, the participants social and cultural context, and their experiences in life will have to be taken into account, in addition to the researcher's own contexts of themselves and the perceptions of the people they are going to study. As Ahearn experienced in her study on the interplay between marriages and the decision making process that comes with it in Nepal, the researcher would have to be aware of their own preconceived notions. (Ahearn 2017, 63). Some individuals might have a unique experience relative to the other participants. So, in those cases, it might be fruitful to be flexible with the research questions since, in linguistic anthropology, questions and patterns develop as the research study is performed.

Each research method has advantages and drawbacks that comes with it. Ahearn argues that these need to be factored into the study as a crucial factor to draw meaningful analyses from the study. Participant observation, Interviews, Surveys and Questionnaires, Recording naturally occurring conversations, experimental methods, matched guise tests, written texts are all useful tools that has to picked and chosen, with full knowledge of their impact on the research, depending on the research question we are asking, depending on the context in which research is going to be conducted, depending on the cultural norms, and most importantly following the ethical norms of the AAA, as vague as it may be.
