* Learning Tamil and English
  The infusion of English into my school years as a required language
  to earn jobs is still troubling me, and one that I think many
  languages have been going through. In Tamil, every pronoun has a
  suffix that indicates respect/acknowledge the age of the person you
  are in conversation with. And, there are unique names(roles) for
  everyone in the family tree. Starting from a very young age, people
  are taught to address everyone with the appropriate respect suffix
  that indicates their age. So, in conversations, it becomes clear who
  is more older/senior than the other. This is especially true among
  siblings. However, it's not uncommon to see siblings not use these
  respectful suffixes. The reason is that disregarding the respect
  among siblings or anyone you feel closer to was a sign of closeness
  between them. Two brothers with age difference of 8 years will still
  call each other using colloquial suffixes. But when they talk to
  someone who is just an year or two older neighbor, they would use
  the respectful suffixes. What happens when you don't the age of the
  person, you are talking to? For example, a postman. If it's an adult
  who is addressing the postman, they will use the respectful suffix
  and if it's a youngster/child where the age difference is visible,
  they would address them as "Anna" meaning brother. It is not
  uncommon call people you just met, Anna(brother), Akka(sister),
  Mama(Uncle), Athai(Aunt). When a child is growing and is invariably
  mistakes and uses incorrect way of addressing someone, the parents
  immediately correct them and ask them to say the correct word right
  away. Most kids during my time were getting introduced to English
  medium of instruction schools and it became the lingua franca in
  schools eventhough the teachers and students weren't as adept in
  using it. It was common to talk to a fellow student in tamil but
  switch to English when you are talking to a teacher.
