**** Which language do you think is their first language? Why?
     I think Spanish is their first language. In the conversation, it appears that they code switch to connect at a deeper level(Pevey 2022, Module 4.3) given that they are talking about a fairly sensitive topic - one's ability to quit or not smoking. This alone is not a sufficient condition to declare Spanish as their first language but the places where person A code switches is more sensitive and when she talks about her own personal social habit. 
  
**** Assuming this little dialogue might be typical of many speakers with these sociolinguistic variables, what might you say about language choice, topic of discourse, and so on, among bilinguals in these situations?
     The speakers live in a multilingual(or a bilingual) society. They choose the dominant language in the society to converse, at first. Here, it happens to be English. They happen to share a cultural/linguistic background that they wish exercise when talking about sensitive topics or when they want to open in a more personal manner without havuing the unfortunate side-effect of anyone listening in and judging person A or person B. The topic of discourse is smoking which is not a socially celebrated act in the society where this conversation happens.
     
**** What we see in this dialogue is formally called "code-switching." We will talk more about code-switching in Chapter 6: Global Communities of Multilingual Users, but, just for fun, why do you think there is code-switching here? What function could this serve in the conversation?
     Two reasons, I can think of
     - They are talking about something that is personal. Possibly, something they consider a weakness. Here code switching happens to connect with the other person beyong the surface level connection.
     - If smoking is not something they are proud or the act of looking into wastepaper basket is something they are proud of, they would want to code switch to just share the information with the person they trust so that noone else may overhear and judge them.
